if(NOT WIN32)
    add_executable(fsn fsn.c fsn_font.h)
else()
    add_executable(fsn WIN32 fsn.c fsn_font.h)
    set_target_properties(fsn PROPERTIES LINK_FLAGS "/ENTRY:\"mainCRTStartup\"")
endif()
if (WIN32)
    target_link_libraries(fsn OpenGL::GL OpenGL::GLU $<IF:$<TARGET_EXISTS:FreeGLUT::freeglut>,FreeGLUT::freeglut,FreeGLUT::freeglut_static>)
else()
    target_link_libraries(fsn $<IF:$<TARGET_EXISTS:FreeGLUT::freeglut>,FreeGLUT::freeglut,FreeGLUT::freeglut_static> OpenGL::GLU OpenGL::GL m)
endif()
target_include_directories(fsn PRIVATE ${OPENGL_INCLUDE_DIRS} ${GLUT_INCLUDE_DIRS})
target_compile_options(fsn PRIVATE ${OPENGL_CFLAGS} ${GLUT_CFLAGS})
target_link_options(fsn PRIVATE ${OPENGL_LDFLAGS} ${GLUT_LDFLAGS})
